services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4176:80"
    depends_on:
      - backend
    restart: always
